# Generated by Django 3.0.2 on 2020-04-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroEquinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comportamiento',
            fields=[
                ('id_comp', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_comp', models.CharField(max_length=255)),
                ('des_comp', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='equino',
            name='comp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroEquinos.Comportamiento'),
        ),
    ]
