# Generated by Django 3.0.2 on 2020-05-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroEquinos', '0002_auto_20200428_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disciplina_Deportiva',
        ),
        migrations.RemoveField(
            model_name='equino',
            name='comp_id',
        ),
        migrations.RemoveField(
            model_name='equino',
            name='raza_id',
        ),
        migrations.RemoveField(
            model_name='historia_clinica',
            name='veterinario_id',
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Comportamiento',
        ),
        migrations.DeleteModel(
            name='Equino',
        ),
        migrations.DeleteModel(
            name='Historia_Clinica',
        ),
        migrations.DeleteModel(
            name='Raza',
        ),
        migrations.DeleteModel(
            name='Veterinario',
        ),
    ]
