# Generated by Django 3.0.2 on 2020-05-02 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroEquinos', '0004_comportamiento_disciplina_deportiva_equino_historia_clinica_prueba_raza_usuarios_veterinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comportamiento',
            name='des_comp',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='comportamiento',
            name='nom_comp',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='disciplina_deportiva',
            name='descripcion_dis',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='disciplina_deportiva',
            name='disciplina',
            field=models.CharField(max_length=255, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='equino',
            name='adv_manejo',
            field=models.CharField(max_length=255, verbose_name='Adv Manejo'),
        ),
        migrations.AlterField(
            model_name='equino',
            name='color',
            field=models.CharField(max_length=255, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='equino',
            name='comp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroEquinos.Comportamiento', verbose_name='Comp'),
        ),
        migrations.AlterField(
            model_name='equino',
            name='fec_nacimiento',
            field=models.DateField(verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='equino',
            name='nom_equino',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='equino',
            name='raza_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroEquinos.Raza', verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='equino',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='estado',
            field=models.CharField(max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='fecha_apertura',
            field=models.DateField(verbose_name='Fecha apertura'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='observaciones',
            field=models.CharField(max_length=255, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='veterinario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroEquinos.Veterinario', verbose_name='Iden. veterinario'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='prueba_campo',
            field=models.CharField(max_length=255, verbose_name='Campo de prueba'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='des_raza',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='nom_raza',
            field=models.CharField(max_length=255, verbose_name='Nombre raza'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='apellidos_veterinario',
            field=models.CharField(max_length=255, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='correo_veterinario',
            field=models.CharField(max_length=255, verbose_name='Correo veterinario'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nombres_veterinario',
            field=models.CharField(max_length=255, verbose_name='Nombres'),
        ),
    ]
